<!DOCTYPE HTML>
<html lang="id">
    <head>
        <title>
            <?php
                // title can be retrieved via property 'title' or method 'getTitle()'
                echo $this->getTitle();
                //~ echo $this->title;
            ?>
        </title>
    </head>
    <body>
        <?php
            // content can be retrieved via property 'content' or method 'getContent()'
            echo $this->getContent();
            //~ echo $this->content;
        ?>
    </body>
</html>
