<!DOCTYPE HTML>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Winata, Content Management System?">
        <meta name="keywords" content="Winata, Content Management System">
        <meta name="author" content="Rendy Eko Prastiyo, and Winata contributors">
        <title><?php
            //~ title can be retrieved via property 'title' or method 'getTitle()'
            echo $this->getTitle();
            //~ echo $this->title;
        ?></title>
        <link rel="shortcut icon" href="/img/favicon.ico" />
        <link rel="stylesheet" href="/css/bootstrap-v3.1.1-min.css" />
        <link rel="stylesheet" href="/css/bootstrap-theme-v3.1.1-min.css" />
        <link rel="stylesheet" href="/css/winata.css" />
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Winata Demo</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                    <form role="form" class="navbar-form navbar-right">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password">
                        </div>
                        <button class="btn btn-success" type="submit">Sign in</button>
                    </form>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <?php
            //~ content can be retrieved via property 'content' or method 'getContent()'
            echo $this->getContent();
            //~ echo $this->content;
        ?>

        <script type="text/javascript" src="/js/jquery-v1.11.0-min.js"></script>
        <script type="text/javascript" src="/js/bootstrap-v3.1.1-min.js"></script>
        <script type="text/javascript" src="/js/winata.js"></script>
    </body>
</html>
